apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deploy
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - app
      containers:
      - name: nginx-deploy
        image: nginx
        imagePullPolicy: IfNotPresent
        resources:
          limits: # Limits must be greater than requests
            memory: "300Mi" # Memory should be reasonable in respect to the receiving node
            cpu: "300m" # CPU should be reasonable in respect to the receiving node
          requests:
            memory: "300Mi"
            cpu: "200m"
